### PR TITLE
update monitoring SG to restrict ingress traffic to VPC CIDR

### PR DESCRIPTION
**Pull request by markdboyd**
## Changes proposed in this pull request:

- update monitoring SG to restrict ingress traffic to VPC CIDR

## security considerations

This change enhances security by removing public access on all ports and limiting access to inbound traffic from the VPC

### CODE REVIEW

**Comment by pburkholder** [comment]
I ❤️ this so much!

**Comment by pburkholder** [comment]
How are the values for `var.vpc_cidr` being set and tested?

**Comment by markdboyd** [comment]
@pburkholder Those values seem to come from the pipeline definition: https://github.com/cloud-gov/cg-provision/blob/main/ci/pipeline.yml#L306. So the values must be in CredHub or a YAML credentials file. 

I'm not sure what you mean by "tested" though

**Review by jameshochadel — APPROVED** [review]
🚀

**Pull request merged**
